config/routes.rb
class LocationByparams
  def self.matches?(request)
    return true if request.params[:latlng] =~ /-?\d+\.\d+,-?\d+\.\d+/

    return true if request.params[:zipcode] =~ /\d{5}/

    return true if request.params[:city] =~ /.+/ && request.params[:state] =~ /[A-Za-z]{2}/

    return false
  end
end

CrisisHelper::Application.routes.draw do
  root to: 'static_pages#landing_page'
  match '/home' => 'static_pages#home'
  match '/contacts' => 'static_pages#contact_list'
  match '/road_conditions' => 'road_conditions#show'
  match '/render_navigation' => 'common#render_navigation'
  match '/schools' => 'schools#index', :as => :schools
  match '/utilities' => 'common#utilities', :as => :utilities
  match '/clear' => 'common#clear', :as => :clear

  match 'locations/:id' => 'locations#show', as: :location
  match 'locations' => 'locations#show', constraints: LocationByparams, as: :location_by_params

  get "local_tweets" => "local_tweets#show"
  get "shelters" => "shelters#show"
  get "noaa" => "noaa_alerts#show"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    redirect_to '/' unless @session.try(:location_id) and (@location = Location.find_by_id(@session.try(:location_id)))

    @hide_back_button = true
    @hide_menu = true
  end

  def landing_page
    # Try to use session
    if @session.try(:location_id)
      @location = Location.find_by_id(@session.try(:location_id))

      render 'static_pages/home'
    end

    # No session, load view with form
    @hide_nav = true
  end

  def handle_invalid_session
    # Skip if we already have a saved location
    return if @session_location

    # Redirect if we didn't find a location
    redirect_to '/' unless @location

    # Create new session
    session = Session.new(:session_hash => request.session_options[:id])
    session.location_id = @location.id
    session.latlng = params[:latlng] unless params[:latlng].blank?
    session.save
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  # from http://zackfern.me/2012/04/10/state-array.html
  def state_list(short=false)
    if short
      return ['AL','AK','AZ','AR','CA','CO','CT','DC', 'DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY']
    else
      return ['Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut','District of Columbia', 'Delaware','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming']
    end
  end
end

app/views/static_pages/_item_list.html.erb
<%= @noaa_alerts.to_yaml %>
<div id="contacts">
  <% [1, 2, 3, 4, 5, 6, 7, 8].each do |i| %>
    <div class="alert alert-info">
      <div class="contact_name"><strong>Red Cross <%= i %></strong></div>
      <div class="number">
        555-555-5555
      </div>
    </div>
  <% end %>
</div>

app/views/static_pages/home.html.erb
<div id="home">
  <%= render :partial => "common/navigation" %>
  <!-- <div>Local Forum</div>  -->
</div>

app/views/static_pages/landing_page.html.erb
<div id="landing-page" class="row">
  <div class="span4 offset4">
    <h2>
      Please enter your location
    </h2>

      <%= form_tag(location_by_params_path, :id => 'location_form') do %>
        <%= field_set_tag do %>
          <div class="control-group">
            <%= text_field_tag(:zipcode, nil, :placeholder => 'Zipcode') %>
          </div>

          <span class="help-block" style="text-align: center;">OR</span>

          <%= text_field_tag(:city, nil, :placeholder => 'City') %>

          <div class="control-group">
            <select name="state">
              <% state_list(true).each do |s| %>
                <option value="<%= s %>"><%= s %></option>
              <% end %>
            </select>
          </div>

          <div class="control-group">
            <%= submit_tag('Submit', :class => 'btn btn-block btn-large btn-danger') %>
          </div>

        <% end %>
      <% end %>
  </div>
</div>